/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DefinirClaveRouteImport } from './routes/definir-clave'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminPoliticasRouteImport } from './routes/_authenticated/admin.politicas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedCategoriaSlugRouteImport } from './routes/_authenticated/categoria.$slug'
import { Route as AuthenticatedPoliticasIndexRouteImport } from './routes/_authenticated/politicas.index'
import { Route as AuthenticatedPoliticasSlugRouteImport } from './routes/_authenticated/politicas.$slug'
import { Route as AuthenticatedProcesoSlugRouteImport } from './routes/_authenticated/proceso.$slug'
import { Route as AuthenticatedAdminProcesoIdRouteImport } from './routes/_authenticated/admin.proceso.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirClaveRoute = DefinirClaveRouteImport.update({
  id: '/definir-clave',
  path: '/definir-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPoliticasRoute =
  AuthenticatedAdminPoliticasRouteImport.update({
    id: '/admin/politicas',
    path: '/admin/politicas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriaSlugRoute =
  AuthenticatedCategoriaSlugRouteImport.update({
    id: '/categoria/$slug',
    path: '/categoria/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoliticasIndexRoute =
  AuthenticatedPoliticasIndexRouteImport.update({
    id: '/politicas/',
    path: '/politicas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoliticasSlugRoute =
  AuthenticatedPoliticasSlugRouteImport.update({
    id: '/politicas/$slug',
    path: '/politicas/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcesoSlugRoute =
  AuthenticatedProcesoSlugRouteImport.update({
    id: '/proceso/$slug',
    path: '/proceso/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProcesoIdRoute =
  AuthenticatedAdminProcesoIdRouteImport.update({
    id: '/admin/proceso/$id',
    path: '/admin/proceso/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/definir-clave': typeof DefinirClaveRoute
  '/admin/politicas': typeof AuthenticatedAdminPoliticasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/categoria/$slug': typeof AuthenticatedCategoriaSlugRoute
  '/politicas/$slug': typeof AuthenticatedPoliticasSlugRoute
  '/proceso/$slug': typeof AuthenticatedProcesoSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/politicas/': typeof AuthenticatedPoliticasIndexRoute
  '/admin/proceso/$id': typeof AuthenticatedAdminProcesoIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/definir-clave': typeof DefinirClaveRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/politicas': typeof AuthenticatedAdminPoliticasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/categoria/$slug': typeof AuthenticatedCategoriaSlugRoute
  '/politicas/$slug': typeof AuthenticatedPoliticasSlugRoute
  '/proceso/$slug': typeof AuthenticatedProcesoSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/politicas': typeof AuthenticatedPoliticasIndexRoute
  '/admin/proceso/$id': typeof AuthenticatedAdminProcesoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/definir-clave': typeof DefinirClaveRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/politicas': typeof AuthenticatedAdminPoliticasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/categoria/$slug': typeof AuthenticatedCategoriaSlugRoute
  '/_authenticated/politicas/$slug': typeof AuthenticatedPoliticasSlugRoute
  '/_authenticated/proceso/$slug': typeof AuthenticatedProcesoSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/politicas/': typeof AuthenticatedPoliticasIndexRoute
  '/_authenticated/admin/proceso/$id': typeof AuthenticatedAdminProcesoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/definir-clave'
    | '/admin/politicas'
    | '/admin/usuarios'
    | '/categoria/$slug'
    | '/politicas/$slug'
    | '/proceso/$slug'
    | '/admin/'
    | '/politicas/'
    | '/admin/proceso/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/definir-clave'
    | '/'
    | '/admin/politicas'
    | '/admin/usuarios'
    | '/categoria/$slug'
    | '/politicas/$slug'
    | '/proceso/$slug'
    | '/admin'
    | '/politicas'
    | '/admin/proceso/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/definir-clave'
    | '/_authenticated/'
    | '/_authenticated/admin/politicas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/categoria/$slug'
    | '/_authenticated/politicas/$slug'
    | '/_authenticated/proceso/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/politicas/'
    | '/_authenticated/admin/proceso/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DefinirClaveRoute: typeof DefinirClaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-clave': {
      id: '/definir-clave'
      path: '/definir-clave'
      fullPath: '/definir-clave'
      preLoaderRoute: typeof DefinirClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/politicas': {
      id: '/_authenticated/admin/politicas'
      path: '/admin/politicas'
      fullPath: '/admin/politicas'
      preLoaderRoute: typeof AuthenticatedAdminPoliticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categoria/$slug': {
      id: '/_authenticated/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof AuthenticatedCategoriaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/politicas/': {
      id: '/_authenticated/politicas/'
      path: '/politicas'
      fullPath: '/politicas/'
      preLoaderRoute: typeof AuthenticatedPoliticasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/politicas/$slug': {
      id: '/_authenticated/politicas/$slug'
      path: '/politicas/$slug'
      fullPath: '/politicas/$slug'
      preLoaderRoute: typeof AuthenticatedPoliticasSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proceso/$slug': {
      id: '/_authenticated/proceso/$slug'
      path: '/proceso/$slug'
      fullPath: '/proceso/$slug'
      preLoaderRoute: typeof AuthenticatedProcesoSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/proceso/$id': {
      id: '/_authenticated/admin/proceso/$id'
      path: '/admin/proceso/$id'
      fullPath: '/admin/proceso/$id'
      preLoaderRoute: typeof AuthenticatedAdminProcesoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminPoliticasRoute: typeof AuthenticatedAdminPoliticasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedCategoriaSlugRoute: typeof AuthenticatedCategoriaSlugRoute
  AuthenticatedPoliticasSlugRoute: typeof AuthenticatedPoliticasSlugRoute
  AuthenticatedProcesoSlugRoute: typeof AuthenticatedProcesoSlugRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedPoliticasIndexRoute: typeof AuthenticatedPoliticasIndexRoute
  AuthenticatedAdminProcesoIdRoute: typeof AuthenticatedAdminProcesoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminPoliticasRoute: AuthenticatedAdminPoliticasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedCategoriaSlugRoute: AuthenticatedCategoriaSlugRoute,
  AuthenticatedPoliticasSlugRoute: AuthenticatedPoliticasSlugRoute,
  AuthenticatedProcesoSlugRoute: AuthenticatedProcesoSlugRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedPoliticasIndexRoute: AuthenticatedPoliticasIndexRoute,
  AuthenticatedAdminProcesoIdRoute: AuthenticatedAdminProcesoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DefinirClaveRoute: DefinirClaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
